### ISSUE TITLE
starter app font

### ISSUE THREAD

**Issue by pageone-capita** [carbon-design-system/carbon-angular-starter#21]
Angular starter app not picking the right font as expected from 
[https://www.carbondesignsystem.com/getting-started/developers/angular](url)

![Capture2](https://user-images.githubusercontent.com/53473726/62883876-0a918e00-bd2d-11e9-832b-daab4ca9f6af.PNG)

My output looks like
![Capture](https://user-images.githubusercontent.com/53473726/62883824-edf55600-bd2c-11e9-919e-ce271b8c57cc.PNG)

**Comment by cal-smith** [comment]
Yep, should be fixed with #20
