### ISSUE TITLE
Menu does not appear in reduced window size

### ISSUE THREAD

**Issue by ksurendra** [carbon-design-system/carbon-angular-starter#30]
Header menu does not appear in reduced window size. 

![Screen Shot 2020-05-20 at 1 34 43 PM](https://user-images.githubusercontent.com/902972/82484935-49185e00-9aa0-11ea-801a-6424715d14fa.png)

![missing](https://user-images.githubusercontent.com/902972/82485234-bf1cc500-9aa0-11ea-9f86-a26a37aea58b.png)

Steps to reproduce:
1. Download code from master branch
2. `npm i`
3. `ng serve`
4. Open the site on a desktop browser `http:\\localhost:4200`
5. Resize the windows size.

**Comment by ksurendra** [comment]
Looks like another similar issue was reported https://github.com/IBM/carbon-components-angular/issues/1140

**Comment by cal-smith** [comment]
Definitly the same issue ... I'm not sure if Carbon exposes classes to prevent the header menus from hiding at a small screen width. It is possible to override the default styles and force the items to be visible at all sizes (though that's obviously not an ideal solution)

**Comment by ksurendra** [comment]
How/where can we override (until this is fixed)? I'm not a css expert :-)

**Comment by cal-smith** [comment]
This snippet from the tutorial should do it: https://github.com/carbon-design-system/carbon-tutorial-angular/blob/angular-step-3/src/assets/scss/carbon-overrides.scss#L24-L27

**Comment by ksurendra** [comment]
Thanks @cal-smith That actually did the trick.

1. Add the below to `/src/styles.scss`
`@import './assets/scss/carbon-override.scss';` 

2. Add a new file  (as) `carbon-override.scss` to folder `/src/assets/scss/` and add the below lines to it.

```
// forces the navigation items to be displayed at all viewport sizes
.bx--header__nav {
	display: block;
}
```
