### ISSUE TITLE
Fixed panels  & Side-nav 

### ISSUE THREAD

**Issue by messaoudi-mounir** [carbon-design-system/carbon-angular-starter#41]
Hi,

I think Side-nav compoent doesn't implement yet the fixed panel.

As descired in the design system docs:
https://carbondesignsystem.com/guidelines/2x-grid/overview
Fixed panels maintain a static width, cannot be collapsed, and also exist outside of the responsive grid.

**Comment by cal-smith** [comment]
I'm not sure where you meant to open this issue. For Carbon issues try here: https://github.com/carbon-design-system/carbon for `carbon-components-angular` issues try here: https://github.com/ibm/carbon-components-angular
