### ISSUE TITLE
How can we add a Footer?  

### ISSUE THREAD

**Issue by ksurendra** [carbon-design-system/carbon-angular-starter#53]
A new project built using this project [Carbon Angular Starter](https://github.com/carbon-design-system/carbon-angular-starter) does not have a Footer.

Is there a way to add one? Or any examples of a footer added to this project?

**Comment by omar-zahid** [comment]
There's no footer component. I would suggest creating a layout module which imports the shell component from carbon and add your footer there if it's need to be on every page.
Start here:
[UI Shell](https://angular.carbondesignsystem.com/?path=/story/components-ui-shell--header)

**Comment by Akshat55** [comment]
Base carbon design system does not have a footer component. I highly recommend looking into a PAL or coordinating with your designer to create a customer footer.
