### ISSUE TITLE
Consider making service workers opt-in while developing

### ISSUE THREAD

**Issue by mderoche** [carbon-design-system/carbon-angular-starter#7]
I understand that this uses service worker and opens the door to all sorts of nifty features, but I also think the way it is implemented here is very intrusive.

After running it for the first time, it hijacks localhost:4200 until you manually clear out my cache.  (For me, at least, even "Empty cache and hard reload" does not remove the hijacking).

For most users, this is _very_ intrusive; its behavior feels like malware before you read further down in the README to learn that you need to run this in a special manner because of the service worker.

Please consider removing it in the future. If not, perhaps a more prominent disclaimer in the README?  Maybe even with instructions to "Update on reload" and "Bypass for network" to prevent this from happening.

**Comment by zvonimirfras** [comment]
We're considering making it opt-in and updating readme to explain the benefits better and how to turn it on.
